### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mustafamamun** [foxel/node-avro-serializer#2]
Can not install with npm install avro-serializer --save getting
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/thecsyco/node-avro-io.git /root/.npm/_git-remotes/git-github-com-thecsyco-node-avro-io-git-1aa6f1d3: Initialized empty Git repository in /root/.npm/_git-remotes/git-github-com-thecsyco-node-avro-io-git-1aa6f1d3/

and many more.

**Comment by PM-Andrey-Kupreychik** [comment]
Looks like some problem with github access from your machine.
Can you _git clone git://github.com/thecsyco/node-avro-io.git_?

**Comment by foxel** [comment]
Looks like some problem with github access from your machine.
Can you _git clone git://github.com/thecsyco/node-avro-io.git?_

**Comment by mustafamamun** [comment]
If I do that I am getting this "Initialized empty Git repository" 

By the way I have also tried to install it by downloading it got the same error.

**Comment by foxel** [comment]
Give some more info about your OS, node.js, npm, git versions

**Comment by mustafamamun** [comment]
I am using CentOS 6.6, node 0.12.2 npm 2.8.3 git 1.7.1

**Comment by foxel** [comment]
Strange.
I've set up vrtual box with CentOS 6.6, installed node 0.12.2, npm 2.8.3, git 1.7.1, also i installed gcc-c++ needed to build node-avro-io
I got installed avro-serializer OK. Please check github connectivity from your machine. Provide full error log - maybe we can find something more

**Comment by mustafamamun** [comment]
The error has changed. Now it is

npm ERR! git fetch -a origin (git://github.com/thecsyco/node-avro-io.git) github.com[0: 192.30.252.130]: errno=Connection timed out
npm ERR! git fetch -a origin (git://github.com/thecsyco/node-avro-io.git) fatal: unable to connect a socket (Connection timed out)
npm ERR! Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "i" "avro-serializer" "--save"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3
npm ERR! code 128

npm ERR! Command failed: git fetch -a origin
npm ERR! github.com[0: 192.30.252.130]: errno=Connection timed out
npm ERR! fatal: unable to connect a socket (Connection timed out)
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:

**Comment by mustafamamun** [comment]
Its kind of strange I can install it from my home but not in my office. Although I can download all other npm package from my office.

**Comment by PM-Andrey-Kupreychik** [comment]
Github connectivity problem.
This package depends on node-avro-io with fixes by @thecsyco. That fixes are still not published to npm node-avro-io package.

**Comment by foxel** [comment]
Github connectivity problem.
This package depends on node-avro-io with fixes by @thecsyco. That fixes are still not published to npm node-avro-io package.
